"""empty message

Revision ID: 6aaac28d0620
Revises: 55b9b3aafcff
Create Date: 2020-04-02 11:48:41.704109

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6aaac28d0620'
down_revision = '55b9b3aafcff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE todos SET completed = False WHERE completed IS NULL")
    op.alter_column("todos", "completed", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
